### ISSUE TITLE
if else if else blocks not rendered correctly when brackets are omitted

### ISSUE THREAD

**Issue by cfurst** [olado/doT#148] opened 2015-03-20 04:11 UTC
Valid js:

``` javascript
if (true && thing)
  return 1;
else if (true && anotherThing) 
  return -1;
else
  return 0;
```

renders:

``` javascript
elsereturn 0;
```

should be:

``` javascript
else return 0;
```

**Comment by epoberezkin** [comment] 2016-10-30 22:21
duplicate of #76, #177

**Closed by epoberezkin** 2016-10-30 22:21 UTC
