### ISSUE TITLE
Better SyntaxError reporting

### ISSUE THREAD

**Issue by fk-hb** [olado/doT#100] opened 2013-11-13 13:24 UTC
I use (and love) dotJS in a growing web application.
This morning, I by mistake deleted ':' in "{{##def.myBlock: blah blah #}}". It took me 15 minutes to figure it out!
No clue how easy or hard to put report usefull errors when parsing but it'll be really very helpfull.

**Comment by epoberezkin** [comment] 2016-10-30 21:51
duplicate of #56, #122

**Closed by epoberezkin** 2016-10-30 21:51 UTC
