### ISSUE TITLE
custom compilation settings behavior

### ISSUE THREAD

**Issue by thorinisme** [olado/doT#243] opened 2017-10-20 10:56 UTC
```javascript
const doT = require('dot');

const text = "{{=it.foo}}\r\nan other line";
const data = { foo: 'bar' };

var template;

console.log(doT.template(text, {strip: false})(data );
// display "{{=it.foo}}\r\nan other line"

console.log(doT.template(text, {...doT.templateSettings, strip: false})(data );
// display "bar\r\nan other line"
```

I suggest `doT.template()` use default settings if property is missing in custom settings.

**Comment by epoberezkin** [comment] 2017-10-20 19:15
duplicate of #174

**Closed by epoberezkin** 2017-10-20 19:15 UTC
