### ISSUE TITLE
Windows: running dottos.cmd with no arguments gives an error 

### ISSUE THREAD

**Issue by wildeyes** [olado/doT#143] opened 2015-02-12 19:39 UTC
``` shell
../website>dottojs.cmd

module.js:340
    throw err;
          ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\dot\bin\dot-packer:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by mlh758** [comment] 2015-06-26 17:41
This is likely related to issue #134 where the dependencies aren't being installed. You can get this running by first doing npm install commander, uglify-js, and mkdirp. That will get this running for you.

**Comment by epoberezkin** [comment] 2016-10-30 23:03
duplicate of #58

**Closed by epoberezkin** 2016-10-30 23:03 UTC
