### ISSUE TITLE
commander is not a devDependency

### ISSUE THREAD

**Issue by jiyinyiyong** [olado/doT#86] opened 2013-07-05 05:19 UTC
As it's not written dependency attribute, `commander` will not be installe from NPM. Running `dottojs` in command line will fail.
https://github.com/olado/doT/blob/master/package.json#L27

**Comment by glukki** [comment] 2015-01-19 17:12
uhm.. up!

**Comment by jiyinyiyong** [comment] 2015-01-19 17:47
Actiallly I alreay gave up using doT and switched my project to React..

**Comment by epoberezkin** [comment] 2016-10-30 21:08
duplicate of #58

**Comment by epoberezkin** [comment] 2016-10-30 21:09
@jiyinyiyong not sure how you can compare library with 40k+ loc and 150 loc...

**Closed by epoberezkin** 2016-10-30 21:08 UTC
Labels: duplicate, needs review

**Comment by jiyinyiyong** [comment] 2016-10-31 02:30
@epoberezkin I send this issue 3 yrs ago and switched it to React a year ago. Probably I will never use doT again.
