### ISSUE TITLE
why not  tip some runtime error?

### ISSUE THREAD

**Issue by qidizi** [olado/doT#108] opened 2013-12-13 03:08 UTC
write some code like that?

var s = new Function('', 'var f = function(){noFunc();};try{f.apply(this,arguments);}catch(e){console.log(f+"runtime error",e)}');
console.log(s,s())

```
        return new Function(c.varname, 'var func=function('+c.varname+'){' +str+ '};try{return func.apply(this,arguments);}catch(e){if (window.console && console.log)console.log(func+" runtime error:",e,"the arguments is:",arguments); else alert(func+" runtime error:"+e); return "temp runtime error!";}');
```

**Comment by epoberezkin** [comment] 2016-10-30 22:18
@qidizi closing the issue.
I think it is a duplicate of #56, #122, etc.
If what you want is to log error instead of throwing exception, you just need to wrap template compilation in try/catch in your code, although usually exception is better.
Please reopen if the issue is different/unanswered.

**Closed by epoberezkin** 2016-10-30 22:18 UTC
