### ISSUE TITLE
please don't clear blank

### ISSUE THREAD

**Issue by qidizi** [olado/doT#107] opened 2013-12-13 02:43 UTC
the html like the:

doT.template('llll&lt;a\t\n\rhref="">blank&lt;/a>kkk') + '';

will echo 

"function anonymous(it) {
var out='llll&lt;ahref=" ">blank&lt;/a>kkk';return out;
}"

the "\t\n\r" will be clear,it is wrong;must be keep they.

**Comment by epoberezkin** [comment] 2016-10-30 22:23
duplicate of #76, #177

**Closed by epoberezkin** 2016-10-30 22:23 UTC
