### ISSUE TITLE
landing page broken

### ISSUE THREAD

**Issue by juji** [olado/doT#293] opened 2020-02-21 13:55 UTC
![Screen Shot 2020-02-21 at 20 56 16](https://user-images.githubusercontent.com/493553/75040104-a37b4000-54ec-11ea-98ec-3ae82f291f81.png)

Your landing page is broken

**Comment by epoberezkin** [comment] 2020-07-25 10:29
I works via http, you do not need https there: http://olado.github.com/doT

This is duplicate of #236

**Closed by epoberezkin** 2020-07-25 10:29 UTC
