### ISSUE TITLE
Dot template breaks for huge json data

### ISSUE THREAD

**Issue by anishnair02** [olado/doT#232] opened 2017-06-02 04:22 UTC
I am using dot.js for one of my projects. Everything was working fine, until I passed a huge-json array to the template.
The view was not rendered. I checked the console, and found this error `Uncaught RangeError: Invalid string length`

To confirm this, I tried passing the first 3 objects from the data array, `data.splice(0, 3)`
And this worked. Then tried it for 6, and no luck.

Is it also because, the engine is trying to loop over large number of records?
Each object in the array is quite huge.

Please help.

**Comment by epoberezkin** [comment] 2017-06-02 10:54
Difficult to say what the problem is without failing code/data samples

**Comment by epoberezkin** [comment] 2017-06-29 11:43
going to close it, please submit the issue with more information.

**Closed by epoberezkin** 2017-06-29 11:43 UTC
