### ISSUE TITLE
Dot template engin vs c or c++ template engines

### ISSUE THREAD

**Issue by topstarnetwork** [olado/doT#132] opened 2014-12-11 00:40 UTC
Hello,
I wanted to change my magento tempalte engine with a high speed cpu low resource feature and I am wondering after some research wich one would suit my project,
it is said that Dot template engin is by far the fastest and the best afterr having read the linkedin report here http://engineering.linkedin.com/frontend/client-side-templating-throwdown-mustache-handlebars-dustjs-and-more and from http://garann.github.io/template-chooser/

But I was told that c or c++ template engines are the fastest such as those once 
http://alexeyrybak.com/blitz/blitz_en.html or http://en.wikipedia.org/wiki/CTPP for php websites,

could someone advise me and explain me the difference amoung the 3 template engines listed here above?

There is some comparison here on http://en.wikipedia.org/wiki/Comparison_of_web_template_engines
Regards, Heather

**Comment by designfrontier** [comment] 2015-02-27 03:17
duplicate of #133 should be closed

**Closed** 2016-10-30 21:42 UTC
