### ISSUE TITLE
template compilation settings should overload

### ISSUE THREAD

**Issue by AlmirKadric** [olado/doT#202] opened 2016-08-28 08:50 UTC
Currently it seems that when custom compiler settings are defined, you are required to specify all settings rather than just the ones you want to overload. This means that you need to copy the existing default `dot.templateSettings` object before applying your changes only to feed it back into the `dot.template` function.

This could be my personal opinion but it would be a lot more natural and usable if the object passed to the `dot.template` function would just overload the defaults for the that specific template.

**Comment by epoberezkin** [comment] 2016-10-30 19:58
@AlmirKadric it makes sense. Old PR tried to address it #51. It's out of date anyway.
Also, it can be done in 2.0.0 to be backward compatible.

**Comment by epoberezkin** [comment] 2016-10-30 20:24
duplicate of #174

**Comment by epoberezkin** [comment] 2017-10-20 19:15
closing as duplicate

**Closed by epoberezkin** 2017-10-20 19:15 UTC
Labels: 2.0.0, duplicate, enhancement
