### ISSUE TITLE
Just a suggestion: Can I Write Some Comment Use doT?

### ISSUE THREAD

**Issue by chenjihu** [olado/doT#165] opened 2015-06-25 07:29 UTC
As the title.  e.g.  {{//this is the comment}} , but it won't be rendered to the browser, which just for developer reading.

**Comment by btpoe** [comment] 2015-07-10 19:42
You can write `{{/* This is a comment */}}`

**Comment by ouadi** [comment] 2015-08-20 14:15
The above solution doesn't work when `dot.templateSettings.strip` is set to `true`.

The code:
```javascript
dot.templateSettings.strip			= true;
dot.templateSettings.append			= false;
dot.templateSettings.selfcontained	= false;
var template = '' +
	'{{/* Some comment*/}}\n' +
	'Hello\n' +
	';';
var compiled = dot.template(template, undefined, {});
console.log(compiled({}));
```

produces:

```
{{}}Hello
```

**Comment by epoberezkin** [comment] 2016-10-30 22:12
duplicate of #135, see answer there.

**Closed by epoberezkin** 2016-10-30 22:12 UTC
